### ISSUE TITLE
Error in deprecation_log (TYPO3 7 LTS) -> feInterface

### ISSUE THREAD

**Issue by bitbruder** [jweiland-net/rlmp_tmplselector#1]
`Usage of feInterface is no longer part of the TYPO3 CMS Core.`

To fix this issue, I removed the third parameter in ext_tables.php, line 37.
https://github.com/jweiland-net/rlmp_tmplselector/blob/master/ext_tables.php#L37

`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('pages', $tempColumns, 1);`

to

`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('pages', $tempColumns);`

More on this here, by Franz Holzinger http://typo3.3.n7.nabble.com/Usage-of-feInterface-is-no-longer-part-of-the-TYPO3-CMS-Core-tp254374p254712.html

**Comment by froemken** [comment]
Hello fgaa,

I have solved this problem with latest patch.

Stefan
