### ISSUE TITLE
TYPO3 7 LTS - Unknown type: selector

### ISSUE THREAD

**Issue by bitbruder** [jweiland-net/rlmp_tmplselector#2]
After trying to use the extension on TYPO3 7 LTS, I've stumbled across another bug. When I try to select a template in the Backend, it shows me this:

![type_select](https://cloud.githubusercontent.com/assets/15855432/11168414/5c142d3e-8b8e-11e5-8f28-84f440fac589.png)

When I change the type to radio in ext_tables.php its working..
https://github.com/jweiland-net/rlmp_tmplselector/blob/master/ext_tables.php#L17

![type_radio](https://cloud.githubusercontent.com/assets/15855432/11168418/8d4c40b2-8b8e-11e5-900f-f2d187b148af.png)

Any ideas?

**Comment by froemken** [comment]
Hello fgaa,

thank you for that issue. TYPO3 7.5 needs an additional renderType. I have implemented it in current version

Stefan
