### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by netbrothers-tr** [jweiland-net/rlmp_tmplselector#3]
Thank you for making this extension available here!

There are no releases of this extension available yet. That's not a problem per se, but it would be a very nice and handy thing. If for instance, a TYPO3 installation works with the extension now, it could well be that it doesn't work with a future version. If said TYPO3 installation breaks one day, we would just have to get the release we used upon installation and a recovery would be much easier.

**Comment by froemken** [comment]
You mean creating a new remote branch for each release like in TYPO3 sourcecode? Like 1.3.2 or do you mean GIT tagging?

**Comment by netbrothers-tr** [comment]
Both approaches would work fine I'd say but Git tagging once in a while would be enough in my opinion while branching could be a bit of an overkill.

**Comment by froemken** [comment]
I haven't understand all the composer features for a long time. It's just a few weeks ago that I learned why tagging is important for composer. I just have updated this extension and added some tags and tested it with a composer based TYPO3. Seems to work now. So have fun working with this extension.
