### ISSUE TITLE
Update Typo3 V9.5?

### ISSUE THREAD

**Issue by gonzalesindie** [jweiland-net/rlmp_tmplselector#5]
Hi there,

Is a new version for TYPO3 9.5 soon available in TER?

Thanks!!

**Comment by froemken** [comment]
Hello @condoridiomas 

I have just released a new version for TYPO3 9 in TER. Please keep me informed, if you find any further problems in this extension.

Stefan

**Comment by gonzalesindie** [comment]
Thanks!
Installed the new version, but now there is the following error when trying to edit page properties of a page: 

Oops, an error occurred!
trim() expects parameter 1 to be string, boolean given

What could that be?

**Comment by froemken** [comment]
Can you please tell me the file and the row number?

**Comment by gonzalesindie** [comment]
EXT/rlmp_tmplselector/Classes/Tca/AbstractAddFiles.php line 161

**Comment by gonzalesindie** [comment]
And:
EXT/rlmp_tmplselector/Classes/Tca/AbstractAddFiles.php line 87

**Comment by froemken** [comment]
Argh. TYPO3 told me that removeFirstAndLastTag will return string, but containing `substr` can return false and string. Ok...thank you, I will create a new release.

**Comment by froemken** [comment]
Ok, I have just release version 3.0.1 to TER and Packagist. Hope it woks now ;-)

Thank you for your support.

Stefan

**Comment by gonzalesindie** [comment]
It works! Vielen Dank! Many thanks!!!!

**Comment by gonzalesindie** [comment]
Hi, there is another bug. When creating a new page. This error message shows up:

**************

An error occurred trying to process items for field "Select template:" (Segment list. of path tt_content./list./20./rlmptmplselector_templateselector./settings. does not exist in array).

*************

Any clues?

Thanks

**Comment by froemken** [comment]
Hello @condoridiomas,

I have just wrapped a catch() around ArrayUtility to prevent throwing this exception. As I don't get this error on my testing machine it's up to you to test that. You can download version 3.0.2 by composer. Hope that is OK for you?

Stefan

**Comment by gonzalesindie** [comment]
Works now under version 3.0.2. Error message gone. 
Thanks!

**Comment by froemken** [comment]
Perfect. I just have release the new version to TER.
